apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api
  labels:
    app: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
        - name: udagram-api
          image: bishop02/udagram-api-feed:v1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: POSTGRES_DB
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: AWS_REGION
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: AWS_BUCKET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: udagram-secrets
                  key: JWT_SECRET
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: udagram-config
                  key: URL

